spring:
  r2dbc:
    url: r2dbc:postgresql://postgres@192.168.99.100:5432/ZWRhLWRlbW8tZGI=
    username: ZWRhLWRlbW8tbG9naW4=
    password: ZWRhLWRlbW8tcGFzc3dvcmQ=
    initialization-mode: always
    pool:
      name: ORDER-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
