kafka:
  bootstrap:
    servers: 192.168.99.100:9092
  producer:
    clientId: order-service-producer
  consumer:
    groupId: order-service-consumer
  streams:
    applicationId: order-service
    sourceTopic: order-topic
    sinkTopic: order-sink-topic
