spring:
  r2dbc:
    # TODO Move credentials to k8s secrets
    url: r2dbc:postgresql://192.168.99.100:30301/eda-demo-db
    username: eda-demo-login
    password: eda-demo-password
    initialization-mode: always
    pool:
      name: ORDER-SERVICE-POOL
      maxSize: 10
      initialSize: 2
      maxIdleTime: 30m
      validationQuery: "SELECT 1"
